project:
  type: website
  output-dir: docs

website:
  title: "Alexis Araujo | Portfolio"
  site-url: https://alexisdaraujoc.github.io/
  
  navbar:
    background: "#0f172a"
    left:
      - href: index.qmd
        text: "Home"
      - text: "Projects"
        menu:
          - text: "Grain Storage Network Optimization"
            href: 30daymapchallenge/day1_points_silos/day1_points_silos.ipynb
          - text: "Agro-Logistics Dynamics"
            # Ruta actualizada para coincidir con tu nueva carpeta y archivo .ipynb
            href: 30daymapchallenge/day2_lines_antpath/day2_lines_antpath.ipynb
      - href: about.qmd
        text: "About Me"

format:
  html:
    theme: darkly
    toc: true
    lang: en

execute:
  freeze: auto