project:
  type: website
  output-dir: docs

website:
  title: "Alexis Araujo | Portfolio"
  site-url: https://alexisdaraujoc.github.io/
  
  navbar:
    background: "#0f172a"
    left:
      - href: index.qmd
        text: "Home"
        
      # PESTAÑA 1: Python & Spatial Data Science
      - text: "Python & Spatial Data Science"
        menu:
          - text: "Spatial Infrastructure Optimization"
            href: python_portfolio/infrastructure_storage_optimization/infrastructure_storage_optimization.ipynb
          - text: "Dynamic Network Analytics"
            href: python_portfolio/dynamic_network_analytics/day2_lines_antpath.ipynb
          
      # PESTAÑA 2: QGIS Cartographic Engineering
      - text: "QGIS Cartographic Engineering"
        menu:
          - text: "Regional Soil Classification (Venezuela)"
            href: index.qmd

      # PESTAÑA 3: ArcGIS Enterprise Solutions
      - text: "ArcGIS Enterprise Solutions"
        menu:
          - text: "Terrain Modeling & Hydrology Showcase"
            href: index.qmd

      - href: about.qmd
        text: "About Me"

format:
  html:
    theme: darkly
    toc: true
    lang: en

execute:
  freeze: auto