project:
  type: website
  output-dir: docs

website:
  title: "Alexis Araujo | Portfolio"
  site-url: https://alexisdaraujoc.github.io/
  
  navbar:
    background: "#0f172a"
    left:
      - href: index.qmd
        text: "Home"
        
      # PESTAÑA 1: Python (Nombre corto, despliega el enfoque avanzado)
      - text: "Python GIS"
        menu:
          - text: "Spatial Infrastructure Optimization"
            href: python_portfolio/infrastructure_storage_optimization/infrastructure_storage_optimization.ipynb
          - text: "Dynamic Network Analytics"
            href: python_portfolio/dynamic_network_analytics/day2_lines_antpath.ipynb
          
      # PESTAÑA 2: QGIS (Nombre corto, listo para el futuro)
      - text: "QGIS"
        menu:
          - text: "Regional Soil Cartography & Classification"
            href: index.qmd

      # PESTAÑA 3: ArcGIS (Nombre corto, listo para el futuro)
      - text: "ArcGIS"
        menu:
          - text: "Enterprise Solutions & Terrain Modeling"
            href: index.qmd

      - href: about.qmd
        text: "About Me"

format:
  html:
    theme: darkly
    toc: true
    lang: en

execute:
  freeze: auto